name: Build and Upload BoringSSL Wheel to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_34_x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone and Build BoringSSL
        run: |
          git clone https://boringssl.googlesource.com/boringssl &&
          cd boringssl &&
          mkdir build &&
          cd build &&
          cmake -DBUILD_SHARED_LIBS=1 .. &&
          make &&
          cp ssl/libssl.so crypto/libcrypto.so /io/boringssl/libs/

      - name: Install Python Dependencies and Build Wheel
        run: |
          yum install -y cmake gcc g++ make &&
          /opt/python/cp312-cp312/bin/python -m ensurepip &&
          /opt/python/cp312-cp312/bin/python -m pip install --upgrade pip setuptools wheel &&
          /opt/python/cp312-cp312/bin/python setup.py bdist_wheel

      - name: Repair Wheel with Auditwheel
        run: |
          /opt/python/cp312-cp312/bin/python -m pip install auditwheel &&
          auditwheel repair dist/*.whl --plat manylinux_2_34_x86_64 -w repaired_dist

      - name: Upload Repaired Wheel to PyPI
        if: success()
        env:
          TWINE_USERNAME: ${{ secrets.USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          /opt/python/cp312-cp312/bin/python -m pip install --upgrade twine &&
          /opt/python/cp312-cp312/bin/python -m twine upload repaired_dist/*.whl

