jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: pypi
    env:
      BASE_VERSION: 0.0.1
      TWINE_USERNAME: ${{ secrets.USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PASSWORD }}
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
      CIBW_SKIP: "pp*_*"

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Clean previous builds
        run: rm -rf wheelhouse/*

      - name: Clone BoringSSL
        run: git clone https://boringssl.googlesource.com/boringssl

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tools
        run: python -m pip install --upgrade pip setuptools wheel twine cibuildwheel

      - name: Build wheels with cibuildwheel
        run: cibuildwheel --platform linux --output-dir wheelhouse

      - name: Show built wheels
        run: ls wheelhouse

      - name: Upload to PyPI
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: python -m twine upload --skip-existing --repository pypi wheelhouse/*.whl

