name: Build and Upload Wheels

on:
  push:
    branches: [ main, master ]
    schedule:
      - cron: '0 0 * * 0'


jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: pypi
    env:
      BASE_VERSION: 0.0.1  # Define the base version here
      TWINE_USERNAME: ${{ secrets.USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PASSWORD }}
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
      CIBW_SKIP: "pp*_*" # skip PyPy

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set unique build version
        run: |
          BASE_VERSION=0.0.6
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          BUILD_VERSION="${BASE_VERSION}.dev${GITHUB_RUN_NUMBER}+g${SHORT_SHA}"
          echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_ENV

      - name: Clone BoringSSL
        run: git clone https://boringssl.googlesource.com/boringssl

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tools
        run: python -m pip install --upgrade pip setuptools wheel twine cibuildwheel

      - name: Build wheels with cibuildwheel
        run: cibuildwheel --platform linux --output-dir wheelhouse

      - name: Show built wheels
        run: ls wheelhouse

      # Only upload on push to main/master
      - name: Upload to PyPI
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: python -m twine upload --repository pypi wheelhouse/*.whl
