name: Build and Upload Wheels

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: pypi
    env:
      # Just temporarily set BUILD_VERSION with run_number; we'll update it after extracting short SHA
      BUILD_VERSION: 0.0.1.dev${{ github.run_number }}
      TWINE_USERNAME: ${{ secrets.USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PASSWORD }}
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
      CIBW_SKIP: "pp*_*" # skip pypy

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      # Extract the short SHA and append to BUILD_VERSION
      - name: Set short SHA
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "BUILD_VERSION=${BUILD_VERSION}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Clone BoringSSL
        run: git clone https://boringssl.googlesource.com/boringssl

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine cibuildwheel

      - name: Build wheels with cibuildwheel
        run: cibuildwheel --platform linux --output-dir wheelhouse

      - name: Show built wheels
        run: ls wheelhouse

      - name: Upload to PyPI
        run: python -m twine upload --repository pypi wheelhouse/*.whl

