name: Build and Upload BoringSSL Wheel to PyPI

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday at 00:00 UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['cp37-cp37m', 'cp38-cp38', 'cp39-cp39', 'cp310-cp310', 'cp311-cp311', 'cp312-cp312']  # Python 3.7 to 3.12
    container:
      image: quay.io/pypa/manylinux_2_34_x86_64

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Clone and Build BoringSSL
      - name: Clone and Build BoringSSL
        run: |
          echo "Building BoringSSL from source..."
          git clone https://boringssl.googlesource.com/boringssl
          cd boringssl
          mkdir build
          cd build
          cmake -DBUILD_SHARED_LIBS=1 ..
          make
          mkdir -p ../boringssl_binary_build/.libs
          cp ssl/libssl.so ../boringssl_binary_build/.libs/
          cp crypto/libcrypto.so ../boringssl_binary_build/.libs/

      # 3. Verify Built Libraries
      - name: Verify Built Libraries
        run: |
          ls -l boringssl_binary_build/.libs

      # 4. Install Python Build Tools
      - name: Install Python Build Tools
        run: |
          /opt/python/${{ matrix.python-version }}/bin/python -m ensurepip
          /opt/python/${{ matrix.python-version }}/bin/python -m pip install --upgrade pip setuptools wheel auditwheel

      # 5. Generate Dynamic Pre-Release Version
      - name: Generate Dynamic Pre-Release Version
        id: version
        run: |
          DATE=$(date +%Y%m%d%H%M%S)
          VERSION=0.0.1.dev${DATE}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # 6. Update setup.py with Pre-Release Version
      - name: Update setup.py with Pre-Release Version
        run: |
          sed -i "s/version='0.0.1'/version='${VERSION}'/" setup.py

      # 7. Build Python Wheel
      - name: Build Python Wheel
        run: |
          /opt/python/${{ matrix.python-version }}/bin/python setup.py bdist_wheel

      # 8. Repair Wheel with Auditwheel
      - name: Repair Wheel with Auditwheel
        run: |
          auditwheel repair dist/*.whl -w repaired_dist

      # 9. Test Built Wheel
      - name: Test Built Wheel
        run: |
          /opt/python/${{ matrix.python-version }}/bin/python -m pip install repaired_dist/*.whl
          /opt/python/${{ matrix.python-version }}/bin/python -c "import boringssl_binary_build; print('Import successful!')"

      # 10. 

