name: Build and Upload BoringSSL Wheel to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run manylinux build
        uses: docker://quay.io/pypa/manylinux_2_34_x86_64
        with:
          entrypoint: /bin/bash
        run: |
          # Ensure the working directory is /io
          cd /io

          # Make build script executable
          chmod +x build.sh

          # Run the build script
          ./build.sh

      - name: Upload built wheel to PyPI
        if: success()
        env:
          TWINE_USERNAME: ${{ secrets.USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python3 -m pip install --upgrade twine
          twine upload dist/*.whl
