name: Build and Upload Wheels

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: pypi
    env:
      BUILD_VERSION: 0.0.1.dev${{ github.run_number }}-${{ github.sha[0:7] }}
      TWINE_USERNAME: ${{ secrets.USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PASSWORD }}
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
      CIBW_SKIP: "pp*_*" # skip pypy if you only want CPython

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      # Clone the BoringSSL repository into ./boringssl directory
      - name: Clone BoringSSL
        run: |
          git clone https://boringssl.googlesource.com/boringssl
          # cd boringssl
          # git checkout <commit-or-branch> # Optional stable version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine cibuildwheel

      - name: Build wheels with cibuildwheel
        run: cibuildwheel --platform linux --output-dir wheelhouse

      - name: Show built wheels
        run: ls wheelhouse

      - name: Upload to PyPI
        run: |
          python -m twine upload --repository pypi wheelhouse/*.whl

