name: Build and Upload Wheels

on:
  push:
    branches: [ master, main ]

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    environment: testpypi
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel auditwheel cmake

      - name: Build BoringSSL from source
        run: |
          echo "Building BoringSSL from source..."
          git clone https://boringssl.googlesource.com/boringssl
          cd boringssl
          mkdir build
          cd build
          cmake -DBUILD_SHARED_LIBS=1 ..
          make -j$(nproc)
          # Create the .libs directory to store built .so files
          mkdir -p ../boringssl_binary_build/.libs
          cp ssl/libssl.so ../boringssl_binary_build/.libs/
          cp crypto/libcrypto.so ../boringssl_binary_build/.libs/
          cd ../..

      - name: List generated libraries
        run: ls -l boringssl/boringssl_binary_build/.libs

      - name: Build wheel
        run: |
          python setup.py bdist_wheel
          auditwheel repair dist/*.whl
          ls wheelhouse/*.whl

      - name: Upload to TestPyPI
        run: |
          python -m pip install twine
          twine upload --verbose --repository testpypi wheelhouse/*manylinux*.whl

