name: Build and Upload BoringSSL Wheel to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_34_x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and run build script
        run: |
          yum install -y cmake gcc g++ make &&
          chmod +x test.sh &&
          ./test.sh

      - name: Upload built wheel to PyPI
        if: success()
        env:
          TWINE_USERNAME: ${{ secrets.USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python3 -m pip install --upgrade twine
          twine upload dist/*.whl
